DROP TABLE HARDWARE;
DROP TABLE HARDWARESTATUS;
DROP TABLE HARDWARETYPE;
DROP TABLE PLANTS;
DROP TABLE PLANTTYPE;
DROP TABLE PLANTSTATUS;
DROP TABLE HARDWARELOGS;

CREATE TABLE HARDWARE (
    HARDWAREKEY INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UNIQUEID VARCHAR(100),
    HARDWARENAME VARCHAR(100),
    HARDWARETYPEKEY INT(6),
    HARDWARESTATUSKEY INT(6),
    TRACKINGPLANTKEY INT(6),
    CREATEDBY VARCHAR(100),
    CREATEDDATE DATETIME,
    UPDATEDBY VARCHAR(100),
    UPDATEDDATE DATETIME,
    ACTIVEFLAG VARCHAR(1)
);

CREATE TABLE HARDWARESTATUS (
    HARDWARESTATUSKEY INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    STATUSNAME VARCHAR(100),
    STATUSCOLOR VARCHAR(100),
    CREATEDBY VARCHAR(100),
    CREATEDDATE DATETIME,
    UPDATEDBY VARCHAR(100),
    UPDATEDDATE DATETIME,
    ACTIVEFLAG VARCHAR(1)
);

CREATE TABLE HARDWARETYPE (
    HARDWARETYPEKEY INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TYPENAME VARCHAR(100),
    CREATEDBY VARCHAR(100),
    CREATEDDATE DATETIME,
    UPDATEDBY VARCHAR(100),
    UPDATEDDATE DATETIME,
    ACTIVEFLAG VARCHAR(1)
);

CREATE TABLE PLANTS (
    PLANTKEY INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PLANTNAME VARCHAR(100),
    PLANTTYPEKEY VARCHAR(100),
    CREATEDBY VARCHAR(100),
    CREATEDDATE DATETIME,
    UPDATEDBY VARCHAR(100),
    UPDATEDDATE DATETIME,
    ACTIVEFLAG VARCHAR(1)
);

CREATE TABLE PLANTTYPE (
    PLANTTYPEKEY INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TYPENAME VARCHAR(100),
    CREATEDBY VARCHAR(100),
    CREATEDDATE DATETIME,
    UPDATEDBY VARCHAR(100),
    UPDATEDDATE DATETIME,
    ACTIVEFLAG VARCHAR(1)
);

CREATE TABLE PLANTSTATUS (
    PLANTSTATUSKEY INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    STATUSNAME VARCHAR(100),
    STATUSCOLOR VARCHAR(100),
    CREATEDBY VARCHAR(100),
    CREATEDDATE DATETIME,
    UPDATEDBY VARCHAR(100),
    UPDATEDDATE DATETIME,
    ACTIVEFLAG VARCHAR(1)
);

CREATE TABLE HARDWARELOGS (
    HARDWARELOGKEY INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    HARDWAREKEY INT(6),
    PLANTKEY INT(6),
    TEMPERATURE INT(6),
    HUMIDITY INT(6),
    PLANTSTATUSKEY INT(6),
    CREATEDBY VARCHAR(100),
    CREATEDDATE DATETIME,
    UPDATEDBY VARCHAR(100),
    UPDATEDDATE DATETIME,
    ACTIVEFLAG VARCHAR(1)
);

-- Default Data
INSERT INTO HARDWARESTATUS (STATUSNAME, STATUSCOLOR, CREATEDBY, CREATEDDATE, ACTIVEFLAG) VALUES
('Connected', '#198754', 'System', NOW(), 'Y'),
('Disconnected', '#dc3545', 'System', NOW(), 'Y');

INSERT INTO PLANTSTATUS (STATUSNAME, STATUSCOLOR, CREATEDBY, CREATEDDATE, ACTIVEFLAG) VALUES
('Dry', '#cd6922', 'System', NOW(), 'Y'),
('Wet', '#26c3cb', 'System', NOW(), 'Y');

INSERT INTO HARDWARETYPE (TYPENAME, CREATEDBY, CREATEDDATE, ACTIVEFLAG) VALUES
('Arduino', 'System', NOW(), 'Y');

-- Test Data
INSERT INTO HARDWARE (UNIQUEID, HARDWARENAME, HARDWARETYPEKEY, HARDWARESTATUSKEY, CREATEDBY, CREATEDDATE, ACTIVEFLAG) VALUES
('SN0001', 'Hardware Device 1', 1, 1, 'System', NOW(), 'Y'),

INSERT INTO HARDWARELOGS (HARDWAREKEY, PLANTKEY, TEMPERATURE, HUMIDITY, PLANTSTATUSKEY, CREATEDBY, CREATEDDATE, ACTIVEFLAG) VALUES
(1, 1, 21, 39, 1, 'System', NOW(), 'Y'),
(1, 1, 22, 41, 1, 'System', NOW(), 'Y'),
(1, 1, 23, 40, 1, 'System', NOW(), 'Y'),
(1, 1, 26, 45, 1, 'System', NOW(), 'Y'),
(1, 1, 27, 46, 1, 'System', NOW(), 'Y'),
(1, 1, 21, 39, 1, 'System', NOW(), 'Y'),
(1, 1, 22, 41, 1, 'System', NOW(), 'Y'),
(1, 1, 23, 40, 1, 'System', NOW(), 'Y'),
(1, 1, 26, 45, 1, 'System', NOW(), 'Y'),
(1, 1, 27, 46, 1, 'System', NOW(), 'Y'),
(1, 1, 21, 39, 1, 'System', NOW(), 'Y'),
(1, 1, 22, 41, 1, 'System', NOW(), 'Y'),
(1, 1, 23, 40, 1, 'System', NOW(), 'Y'),
(1, 1, 26, 45, 1, 'System', NOW(), 'Y'),
(1, 1, 27, 46, 1, 'System', NOW(), 'Y'),
(1, 1, 21, 39, 1, 'System', NOW(), 'Y'),
(1, 1, 22, 41, 1, 'System', NOW(), 'Y'),
(1, 1, 23, 40, 1, 'System', NOW(), 'Y'),
(1, 1, 26, 45, 1, 'System', NOW(), 'Y'),
(1, 1, 27, 46, 1, 'System', NOW(), 'Y');